# Header
menu:
  Home: /../

# Logo Image Source
logo_src: /blog/images/logo.png

# Theme Main Subtitle
subtitle_main:

# Theme Secondary subtitle
susbtitle_secondary: 新潟県の探偵事務所ならシークレットジャパン上越・柏崎

# Footer About Section
about_footer: 新潟県の探偵事務所ならシークレットジャパン上越・柏崎<br>定額1日10万円追加料金なし。浮気調査や不倫調査、婚前調査、素行調査、人探し様々な依頼に対応可。お客様の信頼を第一に対応させていただきます。

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: /blog/images/logo.png

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
#comments:
#  # Disqus comments
#  disqus_shortname: klugjo
#  # Facebook comments
#  facebook:
#    appid:
#    comment_count: 5
#    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
email_url: mailto:secret.japan.joetsu@gmail.com
